name: fichar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # SQLite nativo en móvil:
  sqflite: ^2.3.0

  # SQLite-FFI para desktop:
  sqflite_common_ffi: ^2.0.0

  # SQLite sobre IndexedDB para Web (versión correcta):
  sqflite_common_ffi_web: ^1.0.0  # existe desde la 1.0.0 en pub.dev :contentReference[oaicite:0]{index=0}

  http: ^1.1.0
  path: ^1.9.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  provider: ^6.0.0
  connectivity_plus: ^6.1.4
  geolocator: ^14.0.2
  pdf: ^3.10.1
  printing: ^5.10.0
  path_provider: ^2.0.15
  open_file: ^3.2.1
  uuid: ^4.5.1
  csv: ^5.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_fichar_trivalle.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/iconotrivalle.png
    - assets/images/trivalle.png

dependency_overrides:
  geolocator_android: ^5.0.2
